### PR TITLE
UI/UX changes for Deep PSI Tool

### LINKED ISSUE #143: [Deep PSI] console errors causing execution failures
**Observed Behaviour**: 
Often times, Deep PSI tool fails to return results thereby causing the screen to blank out. This can happen, if one of the requests to _https://thinktanked.org/deep-psi?url=<insert-url-here>_ fails. 
Following error can be seen on the console logs:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'audits') at deep-psi.html?url1=https%3A%2F%2Fwww.ingredion.com%2Fna%2Fen-us%2F&url2=https%3A%2F%2Fwww.ingredion.com%2Fna%2Fen-us%2F:156:53
    at Array.forEach (<anonymous>)
    at deep-psi.html?url1=https%3A%2F%2Fwww.ingredion.com%2Fna%2Fen-us%2F&url2=https%3A%2F%2Fwww.ingredion.com%2Fna%2Fen-us%2F:155:14
    at Array.map (<anonymous>)
    at executePSI (deep-psi.html?url1=https%3A%2F%2Fwww.ingredion.com%2Fna%2Fen-us%2F&url2=https%3A%2F%2Fwww.ingredion.com%2Fna%2Fen-us%2F:153:32)
    at async Promise.all (/tools/deep-psi/index 0)
    at async comparePSI (deep-psi.html?url1=https%3A%2F%2Fwww.ingredion.com%2Fna%2Fen-us%2F&url2=https%3A%2F%2Fwww.ingredion.com%2Fna%2Fen-us%2F:132:26)
```

**Ideal Behaviour**:
1. Deep PSI tool should fail gracefully, returning a suitable error message
2. Execution should not fail because of one bad request

### PR DESCRIPTION
**Pull request by varunmitra**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #143 

Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/deep-psi/deep-psi.html
- After: https://issue-143-2--helix-labs-website--adobe.aem.live/tools/deep-psi/deep-psi.html

### CODE REVIEW

**Review by 3vil3mpir3 — APPROVED** [review]

File: tools/deep-psi/deep-psi.js [hunk 1]
```diff
@@ -0,0 +1,646 @@
...
+
+function stddev(arr) {
+  if (!arr || arr.length < 2) {
+    return 0;
+  }
+  const m = mean(arr);
+  return Math.sqrt(arr.reduce((sq, n) => sq + (n - m) ** 2, 0) / (arr.length - 1));
+}
+
+function lowestCluster(arr) {
```
Comment (fkakatie) [inline tools/deep-psi/deep-psi.js:29]: can you help me understand what is going on here and why?

**Review by fkakatie — APPROVED** [review]
i can't test the functionality presently, but the ui changes seem fine.
